//------------------------------------------------------------------------------
// <auto-generated />
//------------------------------------------------------------------------------
namespace Salek_Portfolio.Admin
{
    public partial class Achievements
    {
        protected global::System.Web.UI.WebControls.Label lblMsgA;

        protected global::System.Web.UI.WebControls.TextBox txtATitle;
        protected global::System.Web.UI.WebControls.TextBox txtAOrg;
        protected global::System.Web.UI.WebControls.TextBox txtADate;
        protected global::System.Web.UI.WebControls.TextBox txtADesc;
        protected global::System.Web.UI.WebControls.TextBox txtAVerify;
        protected global::System.Web.UI.WebControls.TextBox txtAIcon;
        protected global::System.Web.UI.WebControls.TextBox txtAOrder;
        protected global::System.Web.UI.WebControls.CheckBox chkAActive;
        protected global::System.Web.UI.WebControls.Button btnAddA;

        protected global::System.Web.UI.WebControls.GridView gvAchievements;
    }
}
