//------------------------------------------------------------------------------
// <auto-generated />
//------------------------------------------------------------------------------
namespace Salek_Portfolio.Admin
{
    public partial class Projects
    {
        protected global::System.Web.UI.WebControls.Label lblMsgP;

        protected global::System.Web.UI.WebControls.TextBox txtTitle;
        protected global::System.Web.UI.WebControls.TextBox txtDesc;
        protected global::System.Web.UI.WebControls.TextBox txtImage;
        protected global::System.Web.UI.WebControls.TextBox txtLive;
        protected global::System.Web.UI.WebControls.TextBox txtCode;
        protected global::System.Web.UI.WebControls.TextBox txtTags;
        protected global::System.Web.UI.WebControls.TextBox txtOrderP;
        protected global::System.Web.UI.WebControls.CheckBox chkActiveP;
        protected global::System.Web.UI.WebControls.Button btnAddP;

        protected global::System.Web.UI.WebControls.GridView gvProjects;
    }
}
