//------------------------------------------------------------------------------
// <auto-generated />
//------------------------------------------------------------------------------
namespace Salek_Portfolio.Admin
{
    public partial class Skills
    {
        protected global::System.Web.UI.WebControls.Label lblMsg;

        protected global::System.Web.UI.WebControls.TextBox txtNewName;
        protected global::System.Web.UI.WebControls.DropDownList ddlNewCategory;
        protected global::System.Web.UI.WebControls.TextBox txtNewProf;
        protected global::System.Web.UI.WebControls.TextBox txtNewOrder;
        protected global::System.Web.UI.WebControls.CheckBox chkNewActive;
        protected global::System.Web.UI.WebControls.Button btnAdd;

        protected global::System.Web.UI.WebControls.GridView gvSkills;
    }
}
