//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated manually to restore Web Forms designer fields.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Salek_Portfolio
{
    public partial class Login
    {
        protected global::System.Web.UI.WebControls.TextBox txtUser;
        protected global::System.Web.UI.WebControls.TextBox txtPass;
        protected global::System.Web.UI.WebControls.Button btnLogin;
        protected global::System.Web.UI.WebControls.Label lblLoginError;
    }
}
